### ISSUE TITLE
Email address maintances

### ISSUE THREAD

**Issue by janz93** [rubyunconfeu/unconf2019#10]
I would like the add a new email address for the sponsoring stuff.
The idea is to use `sponsoring@rubyunconf.eu`.
We should have a setup how we want to use an email address.
* Be it with [`freshdesh`](https://rubyunconfhh.freshdesk.com) currently there is the support address behind it
 * Be it as IMAP account

This relates to #9 and #8 
@lindtdev @p0wl

**Comment by p0wl** [comment]
What needs to be done to close this issue?

**Comment by janz93** [comment]
I got access dnsdimple and added the mail address
