### ISSUE TITLE
Keep sponsors listed more then a year?

### ISSUE THREAD

**Issue by emrox** [rubyunconfeu/unconf2019#11]
TBD: does it makes sense to list sponsors on the last years homepages longer then a year?

**Comment by janz93** [comment]
Yes In my point of view is the old page an archive.
Also the jsunconf also just leaves the sponsors on [their yearly pages](https://2016.jsunconf.eu/) as well.

**Comment by janz93** [comment]
@emrox is this okay for you?
If so I would close this issue

**Comment by emrox** [comment]
for me it's ok but I think we should discuss these issues with the team on a meeting

**Comment by emrox** [comment]
(or at least with more than 2 people)

**Comment by skrings** [comment]
@emrox @janz93 We should leave the last years conference website untouched including sponsors and links to their websites. From my understanding this is how most conferences handle it.

**Comment by janz93** [comment]
@emrox As we all have a common view on the issue I will close this now. 

Also, I and @skrings are responsible for the sponsoring and will explain it to any sponsor if a question comes up.
