### ISSUE TITLE
[Accessability] Add Email address for accessability issues

### ISSUE THREAD

**Issue by skorbut** [rubyunconfeu/unconf2019#23]
Create an e-mail address to handle accessability requests. To bei put in the accessability Page.

**Comment by janz93** [comment]
@skorbut after looking at the [rust website](https://rome.rustfest.eu/accessibility/), I would also use a `team@` address. This one we already have and it will be forwarded to freshdesk and everyone who wants to additionally be added as well.
Or would you prefer a `accessability@` address?

**Comment by skorbut** [comment]
that should be fine the whole address would be `team@rubyunconf.eu`?

**Comment by janz93** [comment]
yes that is correct
