### ISSUE TITLE
Official sponsoring contact informations

### ISSUE THREAD

**Issue by emrox** [rubyunconfeu/unconf2019#8]
Do we have a official contact email address for potential sponsors? if not we should create one and then add a sponsoring section to the homepage
@janz93 @sören

**Comment by janz93** [comment]
Funny I was thinking about the same thing yesterday and wanted to write to you on the weekend 😅
I would like to use `sponsoring@rubyunconf.eu`. 
But currently, it is not set up.
Maybe @lindtdev or @p0wl could help me with that.
But we should definitely have a section on the homepage where we link to the [sponsoring document](https://docs.google.com/document/d/1ZZlv3luSHikGIDZsTQy3ifg4a7vemqKmm7sLPycb4L4)

**Comment by janz93** [comment]
@emrox I set up the email address.
Could you add a section for the sponsoring part on the homepage?

**Comment by p0wl** [comment]
Right now there is not a single paragraph about "becoming a sponsor" or similar on our website.

**Comment by janz93** [comment]
paragraph for website
https://github.com/rubyunconfeu/2019-website/pull/13

**Comment by skrings** [comment]
Please close this issue.

**Comment by janz93** [comment]
it closed by https://github.com/rubyunconfeu/2019-website/pull/13
